# Basic Site Settings
locale                   : "en-US"
title                    : "Junteng Liu"
title_separator          : "-"
name                     : &name "Junteng Liu"
description              : &description "Junteng Liu's academic homepage"
url                      : https://trips44q.github.io # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "/LJT-Homepage" # the subpath of your site, e.g. "/blog"
repository               : "trips44q/LJT-Homepage"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Junteng Liu"
  pronouns         : # example: "she/her"  
  bio              : "First-year PhD candidate at HKUST NLP Group, advised by Prof. Junxian He. Research focuses on natural language processing and machine learning."
  location         : "Hong Kong"
  employer         : "Hong Kong University of Science and Technology"
  uri              : # URL
  email            : "jliugi@connect.ust.hk" 

  # Academic websites
  academia         : # URL
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  inspire-hep      : # URL
  impactstory      : # URL
  orcid            : # URL
  semantic         : # URL
  ssrn             : # URL
  pubmed           : # URL
  researchgate     : # URL
  scopus           : # URL
  zotero           : # URL


  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "Vicent0205"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  artstation       : # Username
  bluesky          : # Username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : "junteng88716710"
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # Username

# Publication Category - The following the list of publication categories and their headings
publication_category:
  manuscripts:
    title: 'Preprints'
  conferences:
    title: 'Conference Papers'
