# Basic Site Settings
locale                   : "en-US"
title                    : "Junteng Liu"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Junteng Liu"
description              : "Junteng Liu's Homepage"
url                      : "https://trips44q.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/LJT-Homepage" # the subpath of your site, e.g. "/blog"
repository               : "trips44q/LJT-Homepage" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true # false (default)
words_per_minute         : 200
enable_copy_code_button  : false
copyright                : # "copyright" name, defaults to site.title
copyright_holder         : # "copyright" holder, defaults to the site.owner.name
search                   : true # true (default)


# Site Logo
logo: /assets/images/88x88.png

# Analytics
analytics:
  provider               : false # false (default), "google", "open-panel", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true (default), false
  open_panel:
    project_id           :
    key                  :
    site_id              :

# Site Author
author:
  name             : "Junteng Liu"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "First-year PhD candidate at HKUST NLP Group. Research focuses on natural language processing and machine learning."
  location         : "Hong Kong"
  email            : "jliugi@connect.ust.hk"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jliugi@connect.ust.hk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "X (Twitter)"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "X (Twitter)"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"


# Reading Files
include:
  - .htaccess
  - _pages
  - _pages/
  - files
exclude:
  - /files/
  - /tmp/
  - /vendor/
  - /assets/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      share: true

# Morphing ( SEO )
morph:
  search: true
  google:
    verify: # ["google=token"]
  bing:
    verify: # ["msvalidate.01=token"]
  alexa:
    verify: # ["alexa-traffic-token"]
  yandex:
    verify: # ["yandex-verification-token"]
  facebook:
    verify: # ["facebook-token"]
  twitter:
    username: # ["@username"]

# Styling
arc:
  # Controls the default nav width.
  # wide, full, narrow
  width: wide

  # Controls the Tactile Admin sidebar (if installed).
  # enable, disable
  nav: enable

  # This options controls whether to show the welcome bar or not.
  #   false: disable
  #   true: enable (default)
  #   loggedin: only show for logged-in users
  welcome_bar: false

  # Some social features
  social_links: true

  # For search box in navigation
  search: true

  # For lazy loading of images
  lazy_load_images: true

  # For code blocks
  copy_code: true

  # For table of contents in lists.
  #   sticky: table of contents is sticky on desktop and mobile (default)
  #   hide: table of contents is hidden on mobile
  #   normal: table of contents is always shown
  toc: sticky

  # Append link anchors to headings in single pages
  anchor_links: true

  # Some footer text
  #   customize: customize the footer text
  #   hide: hide the footer text
  #   minimal: show the minimal footer text (default)
  #   extended: show the extended footer text
  footer: minimal

# Plugin: jekyll-redirect-from
redirect_from:
  json: true

# Plugin: jekyll-sitemap
sitemap:
  enabled: true

# Plugin: jekyll-feed
feed:
  content: atom

# Plugin: jekyll-paginate
paginate: 5
paginate_path: /page:num/

# Plugin: jekyll-seo-tag
seo:
  indexing:
    links: true

# Plugin: jekyll-include-cache
include_cache:
  enabled: true

# Plugin: jekyll-gist
gist:
  username:
  client_id:
  client_secret:

# Plugin: jekyll-algolia
algolia:
  application_id: # YOUR_APP_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY

# Plugin: jekyll-scholar
scholar:
  style: _bibliography/apa.csl
  locale: en
  sort_by: year
  order: descending
  group_by: type
  group_order: ascending
  details: false
  bibliography_list_tag: ul
  bibliography_item_tag: li
  bibliography_item_prefix:
  bibliography_item_suffix:
  bibliography_template: "{{referenced_file}}"
  query: ""

# Plugin: jekyll-tagging
tag_names:

# site.collections
collections:
  posts:
    output: true
  talkmap:
    output: true
  talks:
    output: true
  publications:
    output: true
  teaching:
    output: true
  pages:
    output: true

# This is the default format.
builds:
    format: html

# Outputting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: false

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# The plugin `jekyll-include-cache` will be enabled, and
# for sites without a Gemfile, the following plugins will be installed.
# If you have a Gemfile, uncomment the following line.
#REMOVE_AFFILIATE_LINKS: true

# This sets the default theme to use for installs without a Gemfile.
remote_theme             : "academicpages/academicpages.github.io"

# The skin.
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt",

# Table of Contents
toc:
  min: 2
  max: 3
  list_number: true

# Site comments (owerwrite)
comments:
  provider: false # false (default)
  disqus:
    shortname:

# Other text
untitled: "(Untitled)"
